### ISSUE TITLE
Add option button to make survey active and inactive

### ISSUE THREAD

**Issue by carlosparadis** [erdl/survey_admin#40]
The new capability of survey_display done on [issue 37](https://github.com/erdl/survey_display/issues/37) should also be editable via survey_admin. @ryantanaka May want to go over with @jygh98 on what it uses in the database (please post here what it uses for future reference too - table/column/value in the cell).

**Comment by ryantanaka** [comment]
3/12 update:

The "add option button to make survey active and inactive" is basically done. Some related cosmetic changes were made as well. Initially, 'button' elements were used to indicate the status of a deployment, but I changed these to labels as the buttons were clickable (labels are not clickable so from a ui standpoint I think its cleaner, but whatever small detail). Green for "active" and grey for "inactive". 

The columns you see below were out of order too so that's been fixed. 

![screenshot from 2018-03-12 10-59-06](https://user-images.githubusercontent.com/19616012/37309262-709bb752-25e4-11e8-834d-4ba3bccba687.png)

Some other changes that will be coming with my PR which related to this. We are using templates for our HTML which is awesome, but it does not include the functionality to include our own stylesheet in the `<head>` tag. Now this can be done from whatever HTML file inherits from `base.html`. 

Another thing I came across was this here: See line 236. Tested it and it is something that still needs to be fixed so I am looking into it. @jygh98 any ideas? I have a few hunches but didn't dive deeply into it yet. 

https://github.com/erdl/survey_admin/blob/49727d1e9bb31e709bc3206896f6098e4aa43c02/ubuntuStation/views.py#L224-L247

@carlosparadis, I'm thinking  to remedy this problem mentioned in the `#TODO` in this PR, or else I'd be technically submitting broken code.. I could open an issue and just reference it in the fixing commit but include it in the current branch I'm working on. Any thoughts? 
 
thanks

**Comment by jygh98** [comment]
@ryantanaka @carlosparadis regarding the #TODO, that portion was previously left from Allie.  So i believed i was able to get edit_deployment working in the following commit.

https://github.com/jygh98/survey_admin/blob/60aaacaff4ea26945714bf05af8aaa17b7b5defe/ubuntuStation/views.py#L224-L256

**Comment by carlosparadis** [comment]
# New Aesthetics

> but it does not include the functionality to include our own stylesheet in the <head> tag. Now this can be done from whatever HTML file inherits from base.html.

What do you mean by this? Could you provide me with a few line references? 

# Bugged code

> @carlosparadis, I'm thinking to remedy this problem mentioned in the #TODO in this PR, or else I'd be technically submitting broken code.. I could open an issue and just reference it in the fixing commit but include it in the current branch I'm working on. Any thoughts?

@ryantanaka If the code has been broke up to this day and is broken in the version control system, I suggest you split the problem in a separate PR than the aesthetics. In fact, I suggest you finish the entire aesthetics PR up to testing into production before trying to solve the issue of line 236. Please clarify if the issue is currently present up to this day or if it has been augmented due to recent changes.

**Comment by ryantanaka** [comment]
@jygh98  sweet thanks, I'll test yours out. Do you know what caused this? And everything was able to update properly in your database? 

@carlosparadis, 
**New Aesthetics** 
The html for each page inherit all of the code from [base.html](https://github.com/erdl/survey_admin/blob/master/ubuntuStation/templates/base.html) so that it doesn't have to be rewritten.  

When an html file wants to inherit it, this line of code is used https://github.com/erdl/survey_admin/blob/49727d1e9bb31e709bc3206896f6098e4aa43c02/ubuntuStation/templates/edit_deployment_form.html#L1

This is is great because we don't have to rewrite that whole blob of code for each new html file we create. 

If I need to reference a CSS file, it needs to be done in the `<head>` tag of the html file, but that's already been filled out. So that the `<head>` tag can be accessed, I added the `{% block head %}` 
into the `<head>` tag of the `base.html` file.  Now in another html file, if I need to include anything specific to that file, I can do something like this:

```
{% block head %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="static/show_deployments.css">
{% endblock %}
```
**BuggedCode** 
The problem has been present up until today but it looks like Jason worked on fixing it so I will take a look at his code. I'll finish up with this PR, then address that separately.

**Comment by jygh98** [comment]
<s>So i believed what the problem was when you were trying to edit a deployment to changes its url_text, i believe url_text was a primary key for the DeployedURL table and url_text was a foreign key from KioskSurvey.  So this is why i updated DeployedURL first then KioskSurvey.  In the original code only KioskSurvey was being updated and for that it would not allow you to update because of the foreign key constraint.  This was from what i remembered, what i did was i tried to update the tables manually in my local database.</s>

Actually i take that back, after looking at the table details it seems like there is no primary-foreign key relation?  Anyway let me know if the code i sent works.

**Comment by carlosparadis** [comment]
@ryantanaka so `block head` is some syntaxsugar to perform inheritance on the html file and add whatever extras you want, right? Make sure to note this somewhere for the next newcomers. 

Ok on Bugged code.

**Comment by ryantanaka** [comment]
@carlosparadis , yup thats basically what it is. I'll make a note of it along with an explanation of our use of html templates.

**Comment by carlosparadis** [comment]
I am closing the issues referring by an old accepted PR. Please re-open if you believe is unfinished.
