### ISSUE TITLE
Document pipeline to deploy web app on local machine

### ISSUE THREAD

**Issue by jygh98** [erdl/survey_admin#5]

**Comment by jygh98** [comment]
plans to package the web app into a virtualenv and setup a minimal database.

**Comment by carlosparadis** [comment]
# Project Dependencies

## Python

@jygh98 As far as the virutalenv is concerned later on, here are the pip's I had to run in order to get that "run.py" going (in this order):

 * pip3 install flask
 * pip3 install Flask-SQLAlchemy
 * pip3 install flask-login
 * pip3 install flask-limiter
 * config.json needs to exist in `survey_admin` folder. File currently resides on the server. I added it to the `.gitignore` just to be safe on commit 0fd7ade and 7e4f4eb. 
 * pip3 install flask_wtf
 * pip3 install passlib
 * pip3 install psycopg2 


These need to be listed in the README as dependencies of this web app, and ideally virtualenv when executed on a new computer would install said dependencies, avoiding having to keep running and looking for the error! 

## Postgres Database 

Additionally: Besides the dump pg_dump can generate, the following roles need to be created in a local database: 
 * eileen
 * sepgroup_nonmsg
 * webuser 
    * Also needs to have permissions `LOGIN` and `WITH PASSWORD`, where the password is the one available in `config.json`. 

## Extra files from our IT Server

The files `survey_admin/config.json` and `survey_admin/ubuntuStation/database.py` needs to be downloaded directly from the server on `/var/www/ubuntuStation/config.json` and `/var/www/ubuntuStation/database.py` respectively. 

With all this `python3 run.py` opens the app on localhost on port 8080 to be accessed on the web-browser. Remember only the full dump will work to access, since the login/pass is also stored in the database.

As you see, quite the clunky process to execute locally. We need to improve on this!

# Some references
 * See [D. Shawley response](https://stackoverflow.com/questions/18270859/do-i-need-to-use-virtualenv-with-vagrant) on Stackoverflow.
   * [About his response on requirements.txt](https://pip.readthedocs.io/en/1.1/requirements.html)

**Comment by carlosparadis** [comment]
The walkthrough has been a bit brushed and moved to the project wiki:

https://github.com/erdl/survey_admin/wiki/Deploy-Locally

I am closing this issue.
