### ISSUE TITLE
Sensitive information shouldn't require code files to not be added on Github

### ISSUE THREAD

**Issue by carlosparadis** [erdl/survey_admin#7]
I find strange that we must exclude files from Github which are part of Flask because passwords and users hard coded. There must be a better way to do this than the one currently being used so we don't need to keep hunting these files from the production server. 

This also adds an extra layer of headache in re-deploying in another local machine (see #5).

**Comment by jygh98** [comment]
@carlosparadis 
Regarding this issue i decided to keep the config,json file as the only file that would contain sensitive information, [similar to how survey_display is to be set up if deployed locally with its config.toml.](https://github.com/erdl/survey_display/wiki/Deploy-Locally)  Because now only config.json would be the only one containing sensitive information, i have modified database.py to now pull the information it needs.  Now when deploying survey_admin locally we would only have to manually add config.json.

**Comment by carlosparadis** [comment]
According to @jygh98 and @ryantanaka file paths were causing file not found the error on production only, likely due to pycharm trying to address locally. Commit 1bfc779 address that. I am closing the issue, please re-open if you believe it is still not solved.

**Comment by carlosparadis** [comment]
@ryantanaka Also rotating this to you!
